# Generated by Django 2.2.3 on 2019-07-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attraction',
            new_name='TouristSpot',
        ),
    ]
