# Generated by Django 2.2.3 on 2019-07-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190709_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='assessment',
            field=models.ManyToManyField(blank=True, to='assessments.Assessment', verbose_name='Avaliações'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='comment',
            field=models.ManyToManyField(blank=True, to='comments.Comment', verbose_name='Comentários'),
        ),
    ]
