# Generated by Django 2.2.3 on 2019-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150, verbose_name='Rua')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=150, verbose_name='Estado')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('latitude', models.IntegerField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.IntegerField(blank=True, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
