# Generated by Django 2.2.3 on 2019-07-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('operating_hours', models.TextField(verbose_name='Horário de Funcionamento')),
                ('minimum_age', models.IntegerField(verbose_name='Idade Mínima')),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações',
                'ordering': ['name'],
            },
        ),
    ]
